/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateHireSmartItemInput = {
  pk: string,
  sk: string,
  tenantId: string,
  entityType: string,
  data?: HireSmartItemDataInput | null,
  id?: string | null,
};

export type HireSmartItemDataInput = {
  Name?: string | null,
  SSOProvider?: string | null,
  RoleStatus?: string | null,
  CulturalValueStatus?: string | null,
  CompetencyStatus?: string | null,
  Category?: string | null,
  PositionStatus?: string | null,
  CandidateNumber?: string | null,
  Status?: string | null,
  ResumeURL?: string | null,
  LinkedInURL?: string | null,
  ActivityCategory?: string | null,
  StartTime?: string | null,
  RawData?: string | null,
  AISummary?: string | null,
  Vote?: string | null,
  Feedback?: string | null,
  FacilitatorId?: string | null,
  HiringManagerId?: string | null,
  InterviewCategory?: string | null,
  ScreeningVote?: string | null,
  AssessmentType?: string | null,
  InterviewerRole?: string | null,
  Text?: string | null,
  Source?: string | null,
  QuestionStatus?: string | null,
  QuestionCreatedDate?: string | null,
  QuestionLastUpdated?: string | null,
  RoleType?: string | null,
  CombinedAISummary?: string | null,
  FinalDecision?: string | null,
  EvidenceCategory?: string | null,
  EvidenceText?: string | null,
  URL?: string | null,
  Duration?: number | null,
  ExerciseResponse?: string | null,
  Date?: string | null,
};

export type ModelHireSmartItemConditionInput = {
  pk?: ModelStringInput | null,
  sk?: ModelStringInput | null,
  tenantId?: ModelStringInput | null,
  entityType?: ModelStringInput | null,
  and?: Array< ModelHireSmartItemConditionInput | null > | null,
  or?: Array< ModelHireSmartItemConditionInput | null > | null,
  not?: ModelHireSmartItemConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  owner?: ModelStringInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type HireSmartItem = {
  __typename: "HireSmartItem",
  pk: string,
  sk: string,
  tenantId: string,
  entityType: string,
  data?: HireSmartItemData | null,
  id: string,
  createdAt: string,
  updatedAt: string,
  owner?: string | null,
};

export type HireSmartItemData = {
  __typename: "HireSmartItemData",
  Name?: string | null,
  SSOProvider?: string | null,
  TenantId?: string | null,
  RoleStatus?: string | null,
  CulturalValueStatus?: string | null,
  CompetencyStatus?: string | null,
  Category?: string | null,
  PositionStatus?: string | null,
  CandidateNumber?: string | null,
  Status?: string | null,
  ResumeURL?: string | null,
  LinkedInURL?: string | null,
  ActivityCategory?: string | null,
  StartTime?: string | null,
  RawData?: string | null,
  AISummary?: string | null,
  Vote?: string | null,
  Feedback?: string | null,
  FacilitatorId?: string | null,
  HiringManagerId?: string | null,
  InterviewCategory?: string | null,
  ScreeningVote?: string | null,
  AssessmentType?: string | null,
  InterviewerRole?: string | null,
  Text?: string | null,
  Source?: string | null,
  QuestionStatus?: string | null,
  QuestionCreatedDate?: string | null,
  QuestionLastUpdated?: string | null,
  RoleType?: string | null,
  CombinedAISummary?: string | null,
  FinalDecision?: string | null,
  EvidenceCategory?: string | null,
  EvidenceText?: string | null,
  URL?: string | null,
  Duration?: number | null,
  ExerciseResponse?: string | null,
  Date?: string | null,
};

export type UpdateHireSmartItemInput = {
  pk?: string | null,
  sk?: string | null,
  tenantId?: string | null,
  entityType?: string | null,
  data?: HireSmartItemDataInput | null,
  id: string,
};

export type DeleteHireSmartItemInput = {
  id: string,
};

export type ModelHireSmartItemFilterInput = {
  pk?: ModelStringInput | null,
  sk?: ModelStringInput | null,
  tenantId?: ModelStringInput | null,
  entityType?: ModelStringInput | null,
  id?: ModelIDInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelHireSmartItemFilterInput | null > | null,
  or?: Array< ModelHireSmartItemFilterInput | null > | null,
  not?: ModelHireSmartItemFilterInput | null,
  owner?: ModelStringInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelHireSmartItemConnection = {
  __typename: "ModelHireSmartItemConnection",
  items:  Array<HireSmartItem | null >,
  nextToken?: string | null,
};

export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelSubscriptionHireSmartItemFilterInput = {
  pk?: ModelSubscriptionStringInput | null,
  sk?: ModelSubscriptionStringInput | null,
  tenantId?: ModelSubscriptionStringInput | null,
  entityType?: ModelSubscriptionStringInput | null,
  id?: ModelSubscriptionIDInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionHireSmartItemFilterInput | null > | null,
  or?: Array< ModelSubscriptionHireSmartItemFilterInput | null > | null,
  owner?: ModelStringInput | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type CreateHireSmartItemMutationVariables = {
  input: CreateHireSmartItemInput,
  condition?: ModelHireSmartItemConditionInput | null,
};

export type CreateHireSmartItemMutation = {
  createHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type UpdateHireSmartItemMutationVariables = {
  input: UpdateHireSmartItemInput,
  condition?: ModelHireSmartItemConditionInput | null,
};

export type UpdateHireSmartItemMutation = {
  updateHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type DeleteHireSmartItemMutationVariables = {
  input: DeleteHireSmartItemInput,
  condition?: ModelHireSmartItemConditionInput | null,
};

export type DeleteHireSmartItemMutation = {
  deleteHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type GetHireSmartItemQueryVariables = {
  id: string,
};

export type GetHireSmartItemQuery = {
  getHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type ListHireSmartItemsQueryVariables = {
  filter?: ModelHireSmartItemFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListHireSmartItemsQuery = {
  listHireSmartItems?:  {
    __typename: "ModelHireSmartItemConnection",
    items:  Array< {
      __typename: "HireSmartItem",
      pk: string,
      sk: string,
      tenantId: string,
      entityType: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ItemsByTenantIdQueryVariables = {
  tenantId: string,
  sk?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelHireSmartItemFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ItemsByTenantIdQuery = {
  itemsByTenantId?:  {
    __typename: "ModelHireSmartItemConnection",
    items:  Array< {
      __typename: "HireSmartItem",
      pk: string,
      sk: string,
      tenantId: string,
      entityType: string,
      id: string,
      createdAt: string,
      updatedAt: string,
      owner?: string | null,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateHireSmartItemSubscriptionVariables = {
  filter?: ModelSubscriptionHireSmartItemFilterInput | null,
  owner?: string | null,
};

export type OnCreateHireSmartItemSubscription = {
  onCreateHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnUpdateHireSmartItemSubscriptionVariables = {
  filter?: ModelSubscriptionHireSmartItemFilterInput | null,
  owner?: string | null,
};

export type OnUpdateHireSmartItemSubscription = {
  onUpdateHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};

export type OnDeleteHireSmartItemSubscriptionVariables = {
  filter?: ModelSubscriptionHireSmartItemFilterInput | null,
  owner?: string | null,
};

export type OnDeleteHireSmartItemSubscription = {
  onDeleteHireSmartItem?:  {
    __typename: "HireSmartItem",
    pk: string,
    sk: string,
    tenantId: string,
    entityType: string,
    data?:  {
      __typename: "HireSmartItemData",
      Name?: string | null,
      SSOProvider?: string | null,
      TenantId?: string | null,
      RoleStatus?: string | null,
      CulturalValueStatus?: string | null,
      CompetencyStatus?: string | null,
      Category?: string | null,
      PositionStatus?: string | null,
      CandidateNumber?: string | null,
      Status?: string | null,
      ResumeURL?: string | null,
      LinkedInURL?: string | null,
      ActivityCategory?: string | null,
      StartTime?: string | null,
      RawData?: string | null,
      AISummary?: string | null,
      Vote?: string | null,
      Feedback?: string | null,
      FacilitatorId?: string | null,
      HiringManagerId?: string | null,
      InterviewCategory?: string | null,
      ScreeningVote?: string | null,
      AssessmentType?: string | null,
      InterviewerRole?: string | null,
      Text?: string | null,
      Source?: string | null,
      QuestionStatus?: string | null,
      QuestionCreatedDate?: string | null,
      QuestionLastUpdated?: string | null,
      RoleType?: string | null,
      CombinedAISummary?: string | null,
      FinalDecision?: string | null,
      EvidenceCategory?: string | null,
      EvidenceText?: string | null,
      URL?: string | null,
      Duration?: number | null,
      ExerciseResponse?: string | null,
      Date?: string | null,
    } | null,
    id: string,
    createdAt: string,
    updatedAt: string,
    owner?: string | null,
  } | null,
};
